---
- name: create redis data directory
  ansible.builtin.file:
    path: "{{ redis_data_dir }}"
    state: directory
    mode: '0755'

- name: re-create redis container for {{ redis_instance_name }}
  docker_container:
    name: "Redis-{{ redis_instance_name }}"
    image: redis:5-alpine
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "{{ redis_instance_port }}:6379"
    volumes:
      - "{{ redis_data_dir }}:/data"