---
- name: include postgres init role for ns
  include_role: 
    name: postgres
    tasks_from: postgres-init-chirpstack-ns
  vars:
    postgres_instance_name: "{{ postgres_name }}"
- name: include postgres deploy role for ns
  include_role: 
    name: postgres
    tasks_from: postgres-deploy
  vars:
    postgres_instance_name: "{{ postgres_name }}"
    postgres_instance_port: "{{ postgres_port }}"

- name: include redis deploy role for ns
  include_role: 
    name: redis
    tasks_from: redis-deploy
  vars:
    redis_instance_name: "{{ redis_name }}"
    redis_instance_port: "{{ redis_port }}"

- name: create chirpstack ns directory
  ansible.builtin.file:
    path: "{{ chirpstack_network_server_dir }}"
    state: directory
    mode: '0755'
- name: copy chirpstack ns config
  ansible.builtin.template:
    src: chirpstack-network-server.toml
    dest: "{{ chirpstack_network_server_dir }}/chirpstack-network-server.toml"
    owner: "{{ chirpstack_owner }}"
    group: "{{ chirpstack_group }}"
    mode: '0644'
- name: re-create chirpstack ns container
  docker_container:
    name: ChirpstackNetworkServer
    image: chirpstack/chirpstack-network-server
    state: started
    recreate: yes
    restart_policy: always
    network_mode: host
    volumes:
      - "{{ chirpstack_network_server_dir }}:/etc/chirpstack-network-server"