---
chirpstack_network_server_dir: /opt/chirpstack-network-server
chirpstack_owner: root
chirpstack_group: root
postgres_name: chirpstack-ns
postgres_port: 5555
redis_name: chirpstack
redis_port: 6666