---
- name: create pihole dir
  ansible.builtin.file:
    path: "{{ pihole_home_dir }}"
    state: directory
    mode: '0755'

- name: create etc-pihole dir
  ansible.builtin.file:
    path: "{{ pihole_home_dir }}/etc-pihole"
    state: directory
    mode: '0755'

- name: create etc-dnsmasq.d dir
  ansible.builtin.file:
    path: "{{ pihole_home_dir }}/etc-dnsmasq.d"
    state: directory
    mode: '0755'

- name: re-create pihole container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    recreate: yes
    restart_policy: always
    ports:
      - "192.168.178.86:53:53/udp"
      - "192.168.178.86:53:53/tcp"
      #- "127.0.0.1:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "192.168.178.86:88:80/tcp"
    env:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "{{ pihole_web_password }}"
    volumes:
      - "{{ pihole_home_dir }}/etc-pihole:/etc/pihole"
      - "{{ pihole_home_dir }}/etc-dnsmasq.d:/etc/dnsmasq.d"