# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.
[integration]
marshaler="json"
[integration.mqtt.auth.generic]
servers=["tcp://192.168.178.86:1883"]
username="{{ mqtt_user }}"
password="{{ mqtt_password }}"
qos=2
[integration.mqtt]
event_topic_template="chirpstack/eu868/gateway/{{ '{{' }} .GatewayID {{ '}}' }}/event/{{ '{{' }} .EventType {{ '}}' }}"
state_topic_template="chirpstack/eu868/gateway/{{ '{{' }} .GatewayID {{ '}}' }}/state/{{ '{{' }} .StateType {{ '}}' }}"
command_topic_template="chirpstack/eu868/gateway/{{ '{{' }} .GatewayID {{ '}}' }}/command/#"
[meta_data]
[meta_data.static]
ip="192.168.178.86"